title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
title: A Blog that reflects my work!
description: A student, A Marketer, A Tech enthusiast and A Agriculturist
